### ISSUE TITLE
Using with Docker on MacOS (and a workaround)

### ISSUE THREAD

**Issue by eth-p** [sp-ricard-valverde/github-act-cache-server#7]
Docker Desktop on MacOS runs the docker engine inside a Linux VM (or Rosetta 2 runtime), which doesn't have access to host networking. As a consequence, the `act` runner can't actually access `localhost:8080`.

```
::debug::getCacheEntry - Attempt 1 of 2 failed with error: connect ECONNREFUSED 127.0.0.1:8080
::debug::Resource Url: http://localhost:8080/_apis/artifactcache/cache?keys=<key>&version=<...>
::debug::getCacheEntry - Attempt 2 of 2 failed with error: connect ECONNREFUSED 127.0.0.1:8080
❌  Failure
```

I'm not sure if you want to implement this directly in the repo, but the workaround I've been using involves creating a separate `act` network. I've given the cache server a fixed hostname, allowing the `act` container to refer to it directly by its hostname.

**Changes to docker-compose.yml**:

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 7924a28..b3a430b 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -5,12 +5,20 @@ services:
       context: .
       args:
         - AUTH_KEY=${ACT_CACHE_AUTH_KEY:?Missing env var ACT_CACHE_AUTH_KEY}
+    hostname: act-cache-server.docker
+    container_name: act-cache-server
     ports:
       - '8080:8080'
+    networks:
+      - act
     volumes:
       - github-act-cache-server-cache:/usr/src/app/.caches
       - github-act-cache-server-db:/usr/local/etc/
       #- ./src:/usr/src/app/src # development
+networks:
+  act:
+    name: act
+    driver: bridge
 volumes:
   github-act-cache-server-cache:
   github-act-cache-server-db:
```

**Changes to .actrc**:
```diff
+ --env ACTIONS_CACHE_URL=http://act-cache-server.docker:8080/
+ --env ACTIONS_RUNTIME_URL=http://act-cache-server.docker:8080/
  --env ACTIONS_RUNTIME_TOKEN=foo
+ --container-options "--network=act"
```

**Comment by sp-ricard-valverde** [comment]
Hi !

Hum, is it for apple silicon Macs ? For intel based ones for sure does work(I'm using one)

**Comment by sp-ricard-valverde** [comment]
If you're using the associated docker-compose file you'll see that the container ports are forwarded to the host, in this setup it should work as well (https://docs.docker.com/desktop/networking/#use-cases-and-workarounds)

**Comment by sp-ricard-valverde** [comment]
I'll take a look into it, seems strange cause it's been working for me in Mac without issues but I don't know if I had a different setup.
I like your solution so I might implement it after the investigation, thanks !

**Comment by eth-p** [comment]
Yep, sorry for not specifying! I made the changes around trying to get this working on my ARM-based Mac running MacOS 13.

It's interesting that this issue only arises under ARM-based machines, though. Act (with the platform flag) runs its containers under amd64, and I'm guessing `act-cache-server` runs under the default architecture, which would be aarch64. Maybe sharing a localhost interface isn't possible between the two architectures?

Or it could be related to using Rosetta 2 for amd64 to aarch64 translation instead of qemu emulation. I'll do some testing later to see if it's a problem with going across architectures or if it's because of Rosetta 2 and get back to you on that.

In either case, though, this workaround solved the issue quite nicely. I was able to shave a ton of time off when locally testing my workflows thanks to this project :)

**Comment by sp-ricard-valverde** [comment]
Apologies for deleting my first answers as I thought they were incomplete.

**Comment by sp-ricard-valverde** [comment]
Could you check if you're having [a similar problem](https://github.com/sp-ricard-valverde/github-act-cache-server/issues/5) ? In your case, that the cache server is binding to an ipv6 interface or other ?

**Comment by eth-p** [comment]
Hey, sorry. Mind if I get back to you some time after the weekend? I have a final in a couple days to study for :(

**Comment by sp-ricard-valverde** [comment]
Of course whenever you've got the time :)

**Comment by eth-p** [comment]
> Could you check if you're having [a similar problem](https://github.com/sp-ricard-valverde/github-act-cache-server/issues/5) ? In your case, that the cache server is binding to an ipv6 interface or other ?

Had the chance to test, and yep, this was the issue! I feel a bit stupid for not remembering that there's an IPv6 loopback interface 😅 

I'll close this issue now. Feel free to incorporate my changes if you feel like they would be helpful, though :)
